import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:klippr/klippr/promotions/application/bloc/promotions_bloc.dart';
import 'package:klippr/klippr/promotions/domain/models/promotion.dart';
import 'package:klippr/klippr/promotions/domain/stores/promotions_store.dart';
import 'package:klippr/klippr/promotions/presentation/views/create_promotion_screen.dart';
import 'package:klippr/klippr/shared/data/network/api_exceptions.dart';
import 'package:klippr/klippr/shared/data/network/result.dart';

void main() {
  testWidgets('create promotion explains QR is generated by consumer redemption', (
    tester,
  ) async {
    await tester.pumpWidget(
      MaterialApp(
        home: BlocProvider(
          create: (_) => PromotionsBloc(_FakePromotionsStore()),
          child: const CreatePromotionScreen(),
        ),
      ),
    );

    await tester.scrollUntilVisible(
      find.text('El QR se genera cuando un consumidor canjea esta promoción'),
      400,
      scrollable: find.byType(Scrollable).first,
    );

    expect(
      find.text('El QR se genera cuando un consumidor canjea esta promoción'),
      findsOneWidget,
    );
    expect(find.byTooltip('Regenerar QR'), findsNothing);
  });
}

class _FakePromotionsStore implements PromotionsStore {
  @override
  Future<Result<List<Promotion>>> loadMine() async => const Success([]);

  @override
  Future<Result<List<Promotion>>> loadActiveMine() async => const Success([]);

  @override
  Future<Result<Promotion>> getById(String id) async =>
      Failure(NotFoundException('Promocion no encontrada.'));

  @override
  Future<Result<String>> create({
    required String title,
    required String description,
    required double discountAmount,
    required DiscountType discountType,
    required DateTime startDate,
    required DateTime endDate,
    required String imageKey,
    int? redemptionCap,
  }) async =>
      const Success('new-promo');

  @override
  Future<Result<void>> update(
    String id, {
    required String title,
    required String description,
    required double discountAmount,
    required DiscountType discountType,
    required DateTime startDate,
    required DateTime endDate,
    required String imageKey,
    int? redemptionCap,
  }) async =>
      const Success(null);

  @override
  Future<Result<void>> delete(String id) async => const Success(null);

  @override
  Future<Result<void>> publish(
    String id, {
    bool isBusinessVerified = true,
  }) async =>
      const Success(null);

  @override
  Future<Result<void>> cancel(String id) async => const Success(null);
}
